Repository storyblok/storyblok-nuxt, pull requests merged in 2023-03, with the labels that each got.

#303 docs: Update Creating & Linking Storyblok components
  README.md
  lib/README.md
Labels: improvement

#296 feat: Typescript support
  lib/.npmrc
  lib/.nuxtrc
  lib/src/module.ts
  lib/src/runtime/plugin.ts
  lib/tsconfig.json
  tsconfig.json
Labels: enhancement

#319 feat: typescript support
  lib/.npmrc
  lib/.nuxtrc
  lib/src/module.ts
  lib/src/runtime/plugin.ts
  lib/tsconfig.json
  playground/nuxt.config.ts
  playground/pages/index.vue
  playground/pages/test.vue
  playground/pages/vcalong.vue
  playground/storyblok/sub/Feature.vue
  playground/storyblok/sub/Grid.vue
  playground/storyblok/sub/Page.vue
  playground/storyblok/sub/Teaser.vue
  playground/tsconfig.json
  tsconfig.json
Labels: enhancement, dx

#347 docs: upgrade readme with regions and props fix
  README.md
  lib/README.md
  package-lock.json
Labels: documentation
