Repository storyblok/storyblok-nuxt, pull requests merged in 2023-07, with the labels that each got.

#486 docs: new bridgeOptions showcase and correct apiOptions to parameters
  README.md
Labels: documentation

#398 fix: refactor the async composable to use native fetch and useState only
  README.md
  cypress/e2e/index.cy.ts
  package-lock.json
  package.json
  playground-e2e/plugins/storyblok.js
  playground/error.vue
  playground/nuxt.config.ts
  playground/package-lock.json
  playground/package.json
  playground/pages/[...slug].vue
  playground/pages/index.vue
  src/module.ts
  src/runtime/composables/useAsyncStoryblok.ts
Labels: bugfix, improvement

#501 🔄 synced file(s) with storyblok/storyblok-js
  .github/ISSUE_TEMPLATE/config.yml
Labels: sync
